version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - chat

  reneschat:
    image: rstriby/reneschat
    restart: always
    ports:
     - 3000
    depends_on:
      - redis
    networks:
      - chat
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "start"] # Hier den gewünschten Startbefehl angeben
  reneschat2:
    image: rstriby/reneschat
    restart: always
    ports:
      - 3000
    depends_on:
      - redis
    networks:
      - chat
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    command: ["npm", "start"] # Hier den gewünschten Startbefehl angeben  
  nginx:
    image: nginx:alpine
    ports:
      - 80:80 # Port 80 auf deinem Host wird auf Port 80 des NGINX-Containers gemappt
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Passe dies an, um deine NGINX-Konfigurationsdatei zu verwenden
    networks:
      - chat
    depends_on:
      - reneschat
      - reneschat2
networks:
  chat:
