version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - chat

  reneschat:
    image: rstriby/reneschat
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - chat
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    #command: ["npm", "start"] # Hier den gewünschten Startbefehl angeben
    command: ["node", "app.js"] # Hier den gewünschten Startbefehl angeben
networks:
  chat:
